_abort			_XOPEN$abort
_access			_$access
_alarm			_$alarm
___assert		_XOPEN$__assert
_catclose		_$catclose
_catgets		_$catgets
_catopen		_$catopen
_cfgetispeed		_$cfgetispeed
_cfgetospeed		_$cfgetospeed
_cfsetispeed		_$cfsetispeed
_cfsetospeed		_$cfsetospeed
_chdir			_$chdir
_chmod			_$chmod
_chown			_$chown
_chroot			_$chroot
_clock			_XOPEN$clock
_close			_$close
_closedir		_$closedir
_creat			_$creat
_crypt			_$crypt
_ctermid		_$ctermid
_cuserid		_$cuserid
_daylight		_XOPEN$daylight
_drand48		_$drand48
__dstzone		_XOPEN$_dstzone
_dup			_$dup
_dup2			_$dup2
_encrypt		_$encrypt
_environ		_$environ
_erand48		_$erand48
_execl			_$execl
_execle			_$execle
_execlp			_$execlp
_execv			_$execv
_execve			_$execve
_execvp			_$execvp
_exit			_XOPEN$exit
_fcntl			_$fcntl
_fdopen			_$fdopen
_fileno			_$fileno
_fork			_$fork
_fpathconf		_$fpathconf
_fstat			_$fstat
_fsync			_$fsync
_ftw			_$ftw
_getcwd			_$getcwd
_getegid		_$getegid
_geteuid		_$geteuid
_getgid			_$getgid
_getgrgid		_$getgrgid
_getgrnam		_$getgrnam
_getgroups		_$getgroups
_getlogin		_$getlogin
_getopt			_$getopt
_getpass		_XOPEN$getpass
_getpgrp		_XOPEN$getpgrp
_getpid			_$getpid
_getppid		_$getppid
_getpwnam		_$getpwnam
_getpwuid		_$getpwuid
_getuid			_$getuid
_getw			_$getw
_hcreate		_$hcreate
_hdestroy		_$hdestroy
_hsearch		_$hsearch
_isascii		_$isascii
_isatty			_$isatty
__isdst			_XOPEN$_isdst
_jrand48		_$jrand48
_kill			_$kill
_lcong48		_$lcong48
_lfind			_$lfind
_link			_$link
_lrand48		_$lrand48
_lsearch		_$lsearch
_lseek			_$lseek
_memccpy		_$memccpy
_mkdir			_$mkdir
_mkfifo			_$mkfifo
_mrand48		_$mrand48
_msgctl			_$msgctl
_msgget			_$msgget
_msgrcv			_$msgrcv
_msgsnd			_$msgsnd
_nice			_XOPEN$nice
_nl_langinfo		_$nl_langinfo
_nrand48		_$nrand48
_open			_$open
_opendir		_XOPEN$opendir
_optarg			_$optarg
_opterr			_$opterr
_optind			_$optind
_pathconf		_$pathconf
_pause			_$pause
_pclose			_$pclose
_pipe			_$pipe
_popen			_$popen
_putenv			_$putenv
_putw			_$putw
_read			_$read
_readdir		_$readdir
#
# rename is an ANSI-specified interface - don't rename (!) it.
#_rename			_$rename
#
_rewinddir		_$rewinddir
_rmdir			_$rmdir
_seed48			_$seed48
_seekdir		_$seekdir
_semctl			_$semctl
_semget			_$semget
_semop			_$semop
_setgid			_$setgid
_setkey			_$setkey
_setpgid		_$setpgid
_setsid			_$setsid
_setuid			_$setuid
_shmat			_$shmat
_shmctl			_$shmctl
_shmdt			_$shmdt
_shmget			_$shmget
_sigaction		_$sigaction
_sigaddset		_$sigaddset
_sigdelset		_$sigdelset
_sigemptyset		_$sigemptyset
_sigfillset		_$sigfillset
_sigismember		_$sigismember
_siglongjmp		_longjmp
_signal			_XOPEN$signal
_sigpending		_$sigpending
_sigprocmask		_$sigprocmask
_sigsuspend		_$sigsuspend
_sleep			_XOPEN$sleep
_srand48		_$srand48
_stat			_$stat
_swab			_$swab
_sysconf		_$sysconf
_tcdrain		_$tcdrain
_tcflow			_$tcflow
_tcflush		_$tcflush
_tcgetattr		_$tcgetattr
_tcgetpgrp		_$tcgetpgrp
_tcsendbreak		_$tcsendbreak
_tcsetattr		_$tcsetattr
_tcsetpgrp		_$tcsetpgrp
_tdelete		_$tdelete
_telldir		_$telldir
_tempnam		_$tempnam
_tfind			_$tfind
_times			_$times
_timezone		_XOPEN$timezone
_toascii		_$toascii
_tsearch		_$tsearch
_ttyname		_$ttyname
_twalk			_$twalk
_tzname			_XOPEN$tzname
_tzset			_XOPEN$tzset
_ulimit			_$ulimit
_umask			_$umask
_uname			_$uname
_unlink			_$unlink
_utime			_$utime
_wait			_$wait
_waitpid		_$waitpid
_write			_$write

_erf			_$erf
_erfc			_$erfc
_gamma			_$lgamma
_hypot			_$hypot
_isnan			_$isnan
_j0			_$j0
_j1			_$j1
_jn			_$jn
_lgamma			_$lgamma
_signgam		_$signgam
_y0			_$y0
_y1			_$y1
_yn			_$yn
# entries by FS 930311 and further on
_mktemp			_$mktemp
_ftruncate		_$ftruncate
_htonl			_$htonl
_htons			_$htons
_sendto			_$sendto
_recvfrom		_$recvfrom
_ntohl			_$ntohl
_socket			_$socket
_sys_errlist		_$sys_errlist
_bind			_$bind
_accept			_$accept
_inet_addr		_$inet_addr
_gethostbyname		_$gethostbyname
_endhostent		_$endhostent
_getservbyname		_$getservbyname
_endservent		_$endservent
_dbm_close		_$dbm_close
_dbm_open		_$dbm_open
_dbm_fetch		_$dbm_fetch
_gethostbyaddr		_$gethostbyaddr
_setregid		_$setregid
_setreuid		_$setreuid
_gettimeofday		_$gettimeofday
_select			_$select
_getpwent		_$getpwent
_endpwent		_$endpwent
_setsockopt		_$setsockopt
_listen			_$listen
_connect		_$connect
_sbrk			_$sbrk
_gethostname		_$gethostname
_initgroups		_$initgroups
_sigsetmask		_$sigsetmask
_sigvec			_$sigvec
