#! /bin/sh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/convers/start,v 1.2 1993-08-01 18:07:22 deyke Exp $

dir=/tmp/c

PATH=.:$PATH

if [ ! -f testconfig ] ; then
	echo ERROR: configuration file \"testconfig\" is missing
	exit 1
fi

if [ -x end ] ; then
	end
fi

rm -rf $dir end
mkdir $dir

host=""
for i in `cat testconfig` ; do
	if [ $i = ";" ] ; then
		conversd -a unix:$dir/$host -c $dir/$host.cnf -dd &
		echo kill -9 $! >> end
		echo $host started
		sleep 2
		host=""
	elif [ X$host = X ] ; then
		host=$i
		echo $host > $dir/$host.cnf
	else
		echo $i unix:$dir/$i >> $dir/$host.cnf
	fi
done
echo rm -rf $dir end >> end
chmod 755 end
