#! /bin/sh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/convers/start,v 1.3 1996-01-22 13:13:30 deyke Exp $

dir=/tmp/c

PATH=.:$PATH

if [ ! -f testconfig ]; then
	echo ERROR: configuration file \"testconfig\" is missing
	exit 1
fi

if [ -x end ]; then
	end
fi

rm -rf $dir end
mkdir $dir

host=""
peers=""
for i in `cat testconfig`; do
	if [ $i = ";" ]; then
		conversd -h $host -c '' -a unix:$dir/$host $peers -dd &
		echo kill -9 $! >> end
		echo $host started
		sleep 2
		host=""
		peers=""
	elif [ X$host = X ]; then
		host=$i
	else
		peers="$peers -p unix:$dir/$i"
	fi
done
echo rm -rf $dir end >> end
chmod 755 end
