#!/bin/sh

sysname=`hostinfo | grep "NeXT" | awk '{print $1 "-" $2}'`

#if [ X$1 = X ]
#then
#  echo $sysname
#  exit 0
#fi

tmp=`hostinfo | grep "NeXT" | cut -d';' -f1`

release=`echo $tmp | awk '{print $3}' | sed 's/://'`
version=`echo $tmp | awk '{print $4 " " $5 " " $6 " " $7 " " $8 " " $9}'`
machine=`hostinfo | grep "^Processor type:" | awk '{print $3}'`
nodename=`hostname`

case $1 in
  -a)
    echo $sysname $nodename $release $version $machine
    exit 1;
	;;
  -m)
    echo $machine
	;;
  -n)
    echo $nodename
	;;
  -r)
    echo $release
	;;
  -s)
    echo $sysname
	;;
  -v)
    echo $version
	;;
  -sr)
    echo $sysname $release
	;;
  *)
    echo $sysname
	;;
esac




