#! /bin/csh -f

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/fixnetrc,v 1.2 1992-10-16 17:56:44 deyke Exp $

set nonomatch

rm -f /tmp/iprt.*
c89 -O -s makeiprt.c -o makeiprt

makeiprt
if ($status) exit 1

foreach i (net.rc.*)
  set file = `expr substr $i 8 999`
  if (-f /tmp/iprt.$file) then
    ex - net.rc.$file <<EOF
      %g/^route add/d
      r /tmp/iprt.$file
      x
EOF
  endif
end

trimfiles

rm -f /tmp/iprt.*
