#! /bin/ksh

# @(#) $Id: fixnetrc,v 1.8 1996-08-12 18:52:58 deyke Exp $

empty=/tmp/tmp$$

rm -f /tmp/iprt.* $empty

echo ' ' > $empty

makeiprt || exit 1

for i in net.rc.*; do
	file=${i#net.rc.}
	if [[ -f /tmp/iprt.$file ]]; then
		ex - net.rc.$file <<EOF
		%g/^route add/d
		r $empty
		r /tmp/iprt.$file
		r $empty
		x
EOF
	fi
done

trimfiles

rm -f /tmp/iprt.* $empty
