#! /bin/csh -f

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/fixnetrc,v 1.3 1993-06-13 18:36:56 deyke Exp $

set nonomatch

rm -f /tmp/iprt.*

makeiprt
if ($status) exit 1

foreach i (net.rc.*)
  set file = `expr substr $i 8 999`
  if (-f /tmp/iprt.$file) then
    ex - net.rc.$file <<EOF
      %g/^route add/d
      r /tmp/iprt.$file
      x
EOF
  endif
end

trimfiles

rm -f /tmp/iprt.*
