#! /bin/csh -f

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/mkrc,v 1.6 1994-06-16 13:14:40 deyke Exp $

foreach i (1 2 3 4)
cat >i$i << EOF

hostname     test$i
ax25 mycall  test$i
ip address   $i.$i.$i.$i
netrom ident test$i

attach asy 7f000001 4713 kissui i 0 256 9600

attach netrom

ax25 route add i default

route add default i

echo refuse
icmp trace on
ip rtimer 100
ip ttl 30
memory debug on
tcp mss 216
tcp window 2048

log /dev/tty
start ax25
start discard
start echo
start ftp
start netrom
start rip
start tcpgate finger
start telnet

netrom links test1 test2 200 permanent
arp add 1.1.1.1 netrom test1
arp add 2.2.2.2 netrom test2

trace i 1111

EOF
end
