#! /bin/ksh

# @(#) $Id: print,v 1.8 1999-04-24 16:08:37 deyke Exp $

option=$1
shift

if [[ -n "$1" ]]; then
	files="../common/setup $*"
else
	files="$(< filelist)"
fi

case $option in
n)
	cat $files | tbl -TX | nroff -mm | col
	;;
t)
	cat $files | tbl | troff -mm
	;;
a)
	cat $files | groff -p -t -mgm -Tascii
	;;
p)
	cat $files | groff -p -t -mgm -Tps
	;;
*)
	echo Option $0 not recognized
	exit 1
	;;
esac
