#! /bin/ksh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/print,v 1.5 1995-06-04 09:36:41 deyke Exp $

if [[ -n "$1" ]]; then
	files="setup $*"
else
	files="$(< filelist)"
fi

case ${0##*/} in
nprint)
	cat $files | tbl -TX | nroff -mm | col
	;;
tprint)
	cat $files | tbl | troff -mm
	;;
aprint)
	cat $files | groff -p -t -mgm -Tascii
	;;
pprint)
	cat $files | groff -p -t -mgm -Tps
	;;
*)
	echo $0 not recognized
	exit 1
	;;
esac
