#! /bin/ksh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/print,v 1.3 1994-08-21 10:17:00 deyke Exp $

if [[ -n "$1" ]] ; then
	files="setup $*"
else
	files="$(< filelist)"
fi

case ${0##*/} in
nprint)
	cat $files | tbl -TX | nroff -mm | col
	;;
tprint)
	cat $files | tbl | troff -mm
	;;
gnprint)
	cat $files | gtbl | gnroff -mgm
	;;
gtprint)
	cat $files | gtbl | groff -mgm
	;;
*)
	echo $0 not recognized
	exit 1
	;;
esac
