#! /bin/ksh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/Attic/tcpcheckin,v 1.1 1994-09-26 15:48:28 deyke Exp $

for dir in $(find ~/tcp -type d -name RCS -print) ; do
	cd $dir/..
	pwd
	ci -l -q RCS/*,v < /dev/null
done
