#! /bin/ksh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/Attic/tcpcheckin,v 1.3 1996-08-11 18:12:12 deyke Exp $

for dir in $(find ~/tcp -type d -name RCS -print); do
	cd $dir/..
	pwd
	ci -l -mNone -q RCS/*,v
done
