#! /bin/bash

rm -f def undef jnk tmp1 suspect
nm --undefined-only --portability src/*.o | awk '/ / {print $1}' | sort -u > undef
for file in src/*.o; do
        nm --defined-only --extern-only --portability $file | awk '/ / {print $1}' | sort -u > def
        comm -23 def undef > tmp1
        if [[ -s tmp1 ]]; then
                echo ' ' >> suspect
                echo "=== $file ===" >> suspect
                echo ' ' >> suspect
                cat tmp1 >> suspect
        fi
done
rm -f def undef jnk tmp1
