#! /bin/ksh

# @(#) $Id: tcpmake,v 1.37 1999-01-27 18:46:54 deyke Exp $

#------------------------------------------------------------------------------

save_file()
{
	if [[ -f $1 ]]; then
		cp -p $1 $1.old
	fi
}

#------------------------------------------------------------------------------

check_file()
{
	if [[ -f $1.old ]]; then
		if cmp -s $1.old $1; then
			rm -f $1
			mv $1.old $1
		else
			rm -f $1.old
		fi
	fi
}

#------------------------------------------------------------------------------

if [[ -x /bin/hp9000s700 ]] && /bin/hp9000s700; then
	export CCOPTS='-z +ESlit'
fi

date=$(date +%y%m%d)

cd ~/tcp/lib; make
cd ~/tcp/tools; make

cd ~/tcp
file=README
save_file $file
sed "s/wampes-....../wampes-$date/g" < $file.old > $file
check_file $file

cd ~/tcp/src
file=version.c
save_file $file
sed "s/WAMPES-....../WAMPES-$date/g" < $file.old > $file
check_file $file

for dir in \
	~/tcp \
	~/tcp/NeXT \
	~/tcp/aos \
	~/tcp/bbs \
	~/tcp/convers \
	~/tcp/doc \
	~/tcp/examples \
	~/tcp/lib \
	~/tcp/src \
	~/tcp/tools \
	~/tcp/util \
	; do
	cd $dir
	file=Makefile
	if [[ -f $file ]]; then
		save_file $file
		CFLAGS='-I../lib' mkmf
		check_file $file
	fi
	for file in *.[ch]; do
		if [[ -f $file && $file != configure.h ]]; then
			case $(grep -F -c '@(#) $Id' $file) in
			0)
				save_file $file
				echo '/* @(#) $Id\c' > $file
				echo '$ */\n' >> $file
				cat $file.old >> $file
				check_file $file
				echo RCS Id inserted in $file
				;;
			1)
				;;
			*)
				echo $file has too many RCS Ids
				;;
			esac
		fi
	done
	trimfiles
done

for manual in bbs bridge netupd smack wampes; do
	cd ~/tcp/manuals/$manual

	file=frontpage
	save_file $file
	sed "s/Version [0-9][0-9][0-9][0-9][0-9][0-9]/Version $date/g" < $file.old > $file
	check_file $file

	file=../../doc/$manual.mm
	save_file $file
	cat $(< filelist) | grep -v '@(#) $Id' > $file
	check_file $file

done

cd ~/tcp/doc
for file in *.gif; do
	save_file $file
done
for manual in bbs bridge netupd smack wampes; do
	file=$manual.html
	save_file $file
	mm2html $manual.mm > $file
	check_file $file
done
for file in *.gif; do
	check_file $file
done

cd ~/tcp/bbs
file=bbs.help
save_file $file
groff -p -t -mgm -Tascii < ~/tcp/doc/bbs.mm | sed 's/.//g' | awk '
	/BBS Reference Manual.*Version/ {
		next
	}
	/^ *CONTENTS *$/ {
		exit
	}
	/^[0-9][0-9]*\.[0-9]* \ / {
		print ""
		print "^" $2
		print ""
		sub("^[0-9][0-9]*\.[0-9]* \ ", "")
		print
		next
	}
	{
		print
	}
' | trim -s | expand > $file
check_file $file

cd ~/tcp
make
mk make

echo '***** tcpmake complete *****'
