#! /bin/csh -f

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/tcpmake,v 1.6 1993-06-13 18:36:57 deyke Exp $

tcpremove
foreach dir ( \
	~/tcp \
	~/tcp/bbs \
	~/tcp/convers \
	~/tcp/doc \
	~/tcp/lib \
	~/tcp/src \
	~/tcp/tools \
	~/tcp/util )
	cd $dir
	if (-f Makefile) then
		cp -p Makefile Makefile.old
		make depend
		if ( { cmp -s Makefile Makefile.old } ) then
			mv Makefile.old Makefile
		else
			rm Makefile.old
		endif
	endif
	trimfiles
end
cd ~/tcp/src
makeall |& tee xxx
cd ~/tcp
make
mk make
