#! /bin/csh -f

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/tcpmake,v 1.5 1993-06-10 09:44:14 deyke Exp $

tcpremove
foreach dir (           \
	~/tcp           \
	~/tcp/bbs       \
	~/tcp/convers   \
	~/tcp/doc       \
	~/tcp/lib       \
	~/tcp/src       \
	~/tcp/tools     \
	~/tcp/util      )
  cd $dir
  if (-f Makefile) make depend
  trimfiles
end
cd ~/tcp/src
makeall |& tee xxx
cd ~/tcp
make
mk make
