#! /bin/csh -f

# @(#) $Id: tcprcs,v 1.3 1996-08-12 18:52:58 deyke Exp $

set nonomatch
set tmp = /tmp/tmp.$$
rm -f $tmp
tcpremove
foreach rcsdir (`find ~/tcp -type d -name RCS -print`)
  cd $rcsdir/..
  set dir = `pwd`
  foreach file (`find * -prune -type f -print`)
    if (! -f RCS/${file},v) echo $rcsdir/${file},v is missing
  end
  foreach file (RCS/*)
    (rcsdiff -kkv $* $file > $tmp) >& /dev/null
    if (! -z $tmp) then
      echo ' '
      echo ============== $dir/$file ==============
      echo ' '
      cat $tmp
    endif
  end
end
rm -f $tmp
