#! /bin/csh -f

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/Attic/tcprcs,v 1.2 1996-08-11 18:17:09 deyke Exp $

set nonomatch
set tmp = /tmp/tmp.$$
rm -f $tmp
tcpremove
foreach rcsdir (`find ~/tcp -type d -name RCS -print`)
  cd $rcsdir/..
  set dir = `pwd`
  foreach file (`find * -prune -type f -print`)
    if (! -f RCS/${file},v) echo $rcsdir/${file},v is missing
  end
  foreach file (RCS/*)
    (rcsdiff $* $file > $tmp) >& /dev/null
    if (! -z $tmp) then
      echo ' '
      echo ============== $dir/$file ==============
      echo ' '
      cat $tmp
    endif
  end
end
rm -f $tmp
