#! /bin/sh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/Attic/trimfiles,v 1.5 1993-02-28 17:35:24 deyke Exp $

PATH=/usr/5bin:$PATH
tmp=tmp$$
if [ ! -f .trimtime ] ; then
  touch 0101000070 .trimtime
fi
for i in `find * -prune -type f '(' \
	-name '*.c'          -o \
	-name '*.h'          -o \
	-name 'Makefile'     -o \
	-name 'doc'          -o \
	-name 'fixnetrc'     -o \
	-name 'genupd'       -o \
	-name 'intro.txt'    -o \
	-name 'ip_routes'    -o \
	-name 'net.rc*'      -o \
	-name 'netrom_links' -o \
	-name 'notes'        -o \
	-name 'smack.ms'        \
	')' -newer .trimtime -print`
do
  echo "$i \c"
  trim -s $i > $tmp
  if cmp -s $i $tmp ; then
    rm -f $tmp
    echo no change
  else
    mv $tmp $i
    echo done
  fi
done
echo x > .trimtime
