#! /bin/sh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/vixxx,v 1.3 1993-03-30 17:23:49 deyke Exp $

tmp=/tmp/tmp$$
sed <xxx >$tmp -e "
  / Error code .* (ignored)/d
  / is up to date/d
  / no change$/d
  /^Make:  Don't know how to make /d
  /^chmod: can/d
  /^cp: cannot create/d
  /^ln: .* are identical/d
  /^mv: /d
  /^rm: .* not removed.  Permission denied/d
"
vi $tmp
rm -f $tmp
