#! /bin/sh

# @(#) $Header: /home/deyke/tmp/cvs/tcp/tools/vixxx,v 1.4 1993-06-10 09:44:16 deyke Exp $

tmp=/tmp/tmp$$
sed <xxx >$tmp -e "
  / Error code .* (ignored)/d
  / done$/d
  / is up to date/d
  / no change$/d
  /^chmod: can/d
  /^cp: cannot create/d
  /^ln: .* are identical/d
  /^mv: /d
  /^rm: .* not removed.  Permission denied/d
"
vi $tmp
rm -f $tmp
